[package]
name = "tui-li"
version = "0.1.0"
edition = "2024"

[features]
default = [ "sqlite" ]
dynamodb = [ "toasty/dynamodb" ]
mysql = [ "toasty/mysql" ]
postgresql = [ "toasty/postgresql" ]
sqlite = [ "toasty/sqlite" ]

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9.2"
normalize-url-rs = "0.2"
url = "2.5.7"
chrono = "0.4.41"
anyhow = "1.0.99"
toasty = { git = "https://github.com/tokio-rs/toasty" }

