services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never   # always build local, never pull
    container_name: tui-li-api
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      RUST_LOG: info
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      DYNAMODB_ENDPOINT: http://dynamodb:8000
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb
    command: [ "tui-li" ]
    restart: unless-stopped

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    # important: include the JAR when overriding the command
    user: "0:0"
    working_dir: /home/dynamodblocal
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data", "-port", "8000" ]
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    restart: unless-stopped

  # Optional web UI at http://localhost:8001
  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
    restart: unless-stopped

volumes:
  dynamodb_data:
