name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  docker:
    needs: tests
    uses: ./.github/workflows/docker.yml
    secrets: inherit  # lets the called workflow use DOCKERHUB_* secrets

  terraform:
    needs: docker
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
