name: Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  docker:
    needs: tests
    uses: ./.github/workflows/docker.yml
    with:
      image_name: ${{ vars.IMAGE_NAME }}   
    secrets: inherit                       
  terraform:
    needs: docker
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
