name: Terraform Apply (Lightsail + DynamoDB)

on:
  workflow_call: { }

jobs:
  tf-apply:
    name: Terraform Apply (Lightsail)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_app_aws_access_key_id: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
      TF_VAR_app_aws_secret_access_key: ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (assume role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gha-terraform-${{ github.run_id }}
          aws-region: ap-southeast-2

      - name: Setup Terraform + Terraform Cloud auth
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Terraform init
        run: terraform -chdir=infra init -input=false

      - name: Terraform plan
        run: |
          terraform -chdir=infra plan -out=tfplan -input=false \
            -var "app_aws_access_key_id=${{ secrets.APP_AWS_ACCESS_KEY_ID }}" \
            -var "app_aws_secret_access_key=${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform apply
        run: |
          terraform -chdir=infra apply -auto-approve tfplan \
            -var "app_aws_access_key_id=${{ secrets.APP_AWS_ACCESS_KEY_ID }}" \
            -var "app_aws_secret_access_key=${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}"
