name: Terraform Apply (Lightsail)

on:
  workflow_call: {}

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6
      - run: terraform -chdir=infra init
      - run: terraform -chdir=infra apply -auto-approve
