name: Runt Tests (Rust + React UI)

on:
  workflow_call: {}

jobs:
  rust-tests:
    name: Run Rust (api/) tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            api -> target

      - name: Test
        run: cargo test --locked --all-features --all-targets --verbose

  ui-tests:
    name: Run React UI (ui/) tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (v22) + Corepack
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      # Yarn Berry (v4) cache
      - name: Cache Yarn 4 artifacts
        uses: actions/cache@v4
        with:
          path: |
            ui/.yarn/cache
            ui/.yarn/unplugged
            ui/.yarn/build-state.yml
            ui/.pnp.cjs
            ui/.pnp.loader.mjs
          key: ui-yarn-${{ runner.os }}-${{ hashFiles('ui/yarn.lock', 'ui/.yarnrc.yml') }}
          restore-keys: |
            ui-yarn-${{ runner.os }}-

      - name: Install deps (immutable)
        run: yarn install --immutable

      # If you use Vite/React Testing Library/Jest, make sure "test" exists in ui/package.json
      - name: Run UI tests
        run: yarn test --ci --watchAll=false

